version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:10.14

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - run: npm install
      - run: npm test
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: ~/repo
          paths: .
  build:
    <<: *defaults
    steps:
      - add_ssh_keys:
          fingerprints: '97:8a:d8:bb:eb:e9:22:7a:22:13:a9:df:8d:9e:17:24'
      - attach_workspace:
          at: ~/repo
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: ls -al
      - run:
          name: Avoid hosts unknown for github
          command: mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
      - run: npm run docs:build
      - run: ls -al
      - run: # git push
          name: push-github
          command: |
            git config --global user.email "1518190293@qq.com"
            git config --global user.name "vnues"
            git add -f docs
            git commit -m 'feat: create docs'
            git push origin `git subtree split --prefix docs/dist master`:gh-pages --force
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - save_cache:
          paths:
            - dist
          key: dist
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - restore_cache:
          keys:
            - dist
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run: ls -al
      - run: npm publish

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - build:
          requires:
            - test
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only:
                - /^v.*/
            branches:
              ignore: /.*/
